schema_version = "1.0.0"
id = "mode_selector"
version = "0.1.1"
name = "mode selector"
tagline = "mode selector"
maintainer = "max"
type = "add-on"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]